### ISSUE TITLE
SSR not working

### ISSUE THREAD

**Issue by TimTom2016** [SorenHolstHansen/leptos_toaster#22]
Problem: If trying to use this crate in a ssr enviroment at the top of the tree, you get the following error
Error Message:
`cannot call wasm-bindgen imported functions on non-wasm targets`

Nice work with the crate, looks awesome. Hope to use it in my webapp. Cheers

**Comment by Figments** [comment]
i'm also encountering this issue

**Comment by TimTom2016** [comment]
#28 Should now fix this Issue. Also it was an Issue on my side because I forgot to set the feature flags in my own project. I found by doing it correctly another issue that is also adressed in the pull request
